// Regenerates src/generated/native-typography-variables.css from the shared web
// typography scale. Run with `bun scripts/generate-typography-tokens.ts`; a test
// fails while the committed file is stale.
import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

import { buildAppTypographyClassesCss } from "../../web/src/lib/appTypography";

const output = fileURLToPath(
  new URL("../src/generated/native-typography-variables.css", import.meta.url),
);
writeFileSync(
  output,
  `/* Generated by scripts/generate-typography-tokens.ts from apps/web/src/lib/appTypography.ts. */\n\n${buildAppTypographyClassesCss(".SliceRoot--font")}`,
);
console.log(`wrote ${output}`);
