import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

import {
  buildThemeCssVariables,
  DEFAULT_THEME_STATE,
  resolveThemePack,
  type ThemeVariant,
} from "../../web/src/theme/theme.logic";

const variants: readonly ThemeVariant[] = ["light", "dark"];
const target = fileURLToPath(
  new URL("../src/generated/native-theme-variables.css", import.meta.url),
);

function statusVariables(variant: ThemeVariant): Record<string, string> {
  if (variant === "light") {
    return {
      "--status-success": "var(--success)",
      "--status-failure": "var(--destructive)",
      "--status-open": "var(--color-decoration-added)",
      "--status-merged": "var(--color-indigo-500)",
      "--status-neutral": "var(--color-zinc-500)",
    };
  }
  return {
    "--status-success": "color-mix(in srgb, var(--success) 72%, var(--color-white))",
    "--status-failure": "color-mix(in srgb, var(--destructive) 72%, var(--color-white))",
    "--status-open": "color-mix(in srgb, var(--color-decoration-added) 72%, var(--color-white))",
    "--status-merged": "color-mix(in srgb, var(--color-indigo-500) 72%, var(--color-white))",
    "--status-neutral": "color-mix(in srgb, var(--color-zinc-500) 72%, var(--color-white))",
  };
}

const blocks = variants.map((variant) => {
  const build = buildThemeCssVariables(resolveThemePack(DEFAULT_THEME_STATE, variant), variant, {
    electron: false,
    systemUiFont: DEFAULT_THEME_STATE.systemUiFont,
  });
  const variables = {
    ...build.variables,
    ...statusVariables(variant),
  };
  const declarations = Object.entries(variables)
    .toSorted(([left], [right]) => left.localeCompare(right))
    .map(([name, value]) => `  ${name}: ${value};`)
    .join("\n");
  return `.SliceRoot--theme-${variant} {\n${declarations}\n}`;
});

const output = `/*
 * GENERATED by scripts/generate-native-theme-css.ts.
 * Source: apps/web/src/theme/theme.logic.ts DEFAULT_THEME_STATE.
 * Native uses the opaque material branch because Lynxtron does not expose the
 * Web Electron vibrancy/backdrop contract. Do not edit by hand.
 */

${blocks.join("\n\n")}
`;

writeFileSync(target, output);
